version: "3.7"
name: calculation-system

services:
  server:
    build:
      context: ../..
      dockerfile: ./cmd/server/Dockerfile
    environment:
      APP_ENV: development
      PORT: 8080
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: calculation-service
      JWT_SECRET: secret
      # You first need to register on https://api.random.org/dashboard and get your own API key
      RANDOM_ORG_API_KEY: 00000000-0000-0000-0000-000000000000
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080

  database:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:7.1
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@calculation-system.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - database

volumes:
  postgres-data:
  pgadmin-data:

networks:
  default:
    name: calculation-system
  calculation-system:
    driver: bridge