version: "3.7"
name: calculation-system-service

services:
  calculation-system-service:
    build:
      context: ../../..
      dockerfile: ./cmd/server/Dockerfile
    environment:
      APP_ENV: development
      PORT: 8080
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: calculation-service
      JWT_SECRET: secret
      # You first need to register on https://api.random.org/dashboard and get your own API key
      RANDOM_ORG_API_KEY: 00000000-0000-0000-0000-000000000000
    restart: always
    ports:
      - 8080:8080
    networks:
      - calculation-system-database

networks:
  default:
    name: calculation-system-service
  calculation-system-service:
    driver: bridge
  calculation-system-database:
    external: true
